version: '3.5'

services:
  web:
    container_name: docker-mern
    build: .
    command: yarn start
    ports:
      - "3000:3000"
    links:
      - mongo
    volumes:
      - ./:/usr/src/app

  mongo:
    container_name: mongo-docker-mern
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: netmarket
      MONGO_INITDB_ROOT_USERNAME: netmarketroot
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - mongo-data:/data/db
    networks:
      - mongo
    ports:
      - "27017:27017"

  mongo-express:
    container_name: mongo-express-docker-mern
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_AUTH_DATABASE: netmarket
      ME_CONFIG_MONGODB_ADMINUSERNAME: netmarketroot
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - mongo-data:/data/db
    networks:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8081:8081"

networks:
  mongo:
    name: mongo-network-mern

volumes:
  mongo-data:
