version: '3.5'

services:
  web:
    container_name: "docker-<app-name>"
    build: .
    command: yarn start
    ports:
      - "3000:3000"
    networks:
      - mongo
    volumes:
      - ./:/usr/src/app

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: <db-name>
      MONGO_INITDB_ROOT_USERNAME: <db-username>
      MONGO_INITDB_ROOT_PASSWORD: <db-password>
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - mongo-data:/data/db
    networks:
      - mongo
    depends_on:
      - web
    ports:
      - "27017:27017"

  mongo-express:
    container_name: "mongo-express-docker-<app-name>"
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      ME_CONFIG_MONGODB_AUTH_DATABASE: <db-name>
      ME_CONFIG_MONGODB_ADMINUSERNAME: <db-user>
      ME_CONFIG_MONGODB_ADMINPASSWORD: <db-pass>
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - mongo-data:/data/db
    networks:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8081:8081"

networks:
  mongo:
    name: "mongo-network-<app-name>"

volumes:
  mongo-data:
